server:
    port: 8080
#Establecemos el perfil que dejaremos activo (será el documento con la configuración para ambiente DEV)
spring:
    profiles:
        active: prd

---
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#DOCUMENTO 2: PERFIL "dev"
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
spring:
    config:
        active:
            on-profile: dev
    application:
        name: restfull-api
    datasource:
        password: admin
        url: jdbc:postgresql://localhost:5432/db_restfulapi
        username: postgres
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

---
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#DOCUMENTO 3: PERFIL "qa"
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
spring:
    config:
        active:
            on-profile: qa
    application:
        name: restfull-api
    datasource:
        password: admin
        url: jdbc:postgresql://localhost:5432/db_restfulapi_qa
        username: postgres
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

---
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#DOCUMENTO 4: PERFIL "prd"
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
spring:
    config:
        active:
            on-profile: prd
    application:
        name: restfull-api
    datasource:
        password: admin
        url: jdbc:postgresql://localhost:5432/db_restfulapi_prd
        username: postgres
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

---
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#DOCUMENTO 5: PERFIL "prd-mysql"
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
spring:
    config:
        active:
            on-profile: prd-mysql
    application:
        name: restfull-api
    datasource:
        password:
        url: jdbc:mysql://localhost:3306/db_restfulapi_prd
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true